"""add deny reason

Revision ID: b7a5847ee79b
Revises: 7c04e846c3d0
Create Date: 2025-11-22 16:58:18.350369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a5847ee79b'
down_revision: Union[str, None] = '7c04e846c3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('deny_reason', sa.String(length=255), server_default=sa.text('NULL'), nullable=True))
    op.drop_index(op.f('idx_tracks_artist_trgm'), table_name='tracks', postgresql_ops={'artist': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_tracks_title_trgm'), table_name='tracks', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tracks_title_trgm'), 'tracks', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_tracks_artist_trgm'), 'tracks', ['artist'], unique=False, postgresql_ops={'artist': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('tracks', 'deny_reason')
    # ### end Alembic commands ###
